### PR TITLE
use plugin_setting DSL to get config

### PR DESCRIPTION
**Pull request by SysPete**
Was: $config = $dsl->config->{plugins}{JWT};

Minimal change for compat with plugin2

### CODE REVIEW

**Comment by ambs** [comment]
Thank you. Is the new plugin system in the wild already? :)

**Comment by SysPete** [comment]
Getting close to release with compat layer; atm just trying to make sure we don't have breakages with existing plugins so we can get it out of the door.

**Comment by ambs** [comment]
ok. Will try if this patch works with ^current^ version. If it does, I'll release a new version.
If not, will wait for Dancer2 new release :)

**Comment by ambs** [comment]
0.005 in its way to cpan. Thanks

**Comment by SysPete** [comment]
Excellent! Many thanks.

**Comment by ambs** [comment]
I am the one needing to thank :)

**Pull request merged**
